apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
spec:
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: backend
          image: msjbhinder/mern-chatbot-backend:v2
