apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../base/backend
  - ../base/frontend
  - ../base/database
  - ../base/configmap.yaml
  - ../base/secrets.yaml

patches:
  - path: patch_backend_prod.yaml
    target:
      kind: Deployment
      name: backend
  - path: patch_frontend_prod.yaml
    target:
      kind: Deployment
      name: frontend

commonLabels:
  env: prod
