services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - COOKIE_SECRET=QeThWmZq4t7w!z%C*F-J@NcRfUjXn2r
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
