apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: msjbhinder/mern-chatbot-frontend:prod
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
