apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: dev
patchesStrategicMerge:
  - patch_backend_dev.yaml
  - patch_frontend_dev.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../base/backend
- ../base/frontend
- ../base/database
- ../base/configmap.yaml
- ../base/secrets.yaml

patches:
- path: patch_backend_dev.yaml
  target:
    kind: Deployment
    name: backend
- path: patch_frontend_dev.yaml
  target:
    kind: Deployment
    name: frontend

commonLabels:
  env: dev