apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database/statefulset.yaml
  - ./database/service.yaml
  - ./database/pvc.yaml
  - ./backend/deployment.yaml
  - ./backend/service.yaml
  - ./frontend/deployment.yaml
  - ./frontend/service.yaml
  - ./frontend/ingress.yaml
  - ./configmap.yaml
  - ./secrets.yaml

commonLabels:
  app: mern-chatbot
  tier: ai-saas
