apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://msjbhinder:X8d2oHLA5rPb9AGQ@cluster0.pvthtaq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "9f8d7e2a3c5b4a1f6e0d9c8b7a6e5d4c"
