apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdA== # root (base64 encoded)
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ= # password (base64 encoded)
  JWT_SECRET: c2VjcmV0a2V5 # secretkey (base64 encoded)
