apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-chatbot-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  project: default
  source:
    repoURL: https://github.com/your-username/mern-chatbot-ai-saas.git
    path: k8s/overlays/production
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m