apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: frontend-resource-limits.yaml
    target:
      kind: Deployment
      name: frontend
  - path: backend-resource-limits.yaml
    target:
      kind: Deployment
      name: backend
